apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 14Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cloud-ssd
  awsElasticBlockStore:
    volumeID: vol-06f7fc1012282434b
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 14Gi
  volumeName: jenkins-pv  # Bind to the existing PV
  storageClassName: cloud-ssd  # Ensure this matches your setup if necessary
