apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-config
data:
  config.js: |
    window.env = {
        API_URL: "http://af2e7f7ad53c44a85ba5d7b0272704ad-1589801492.eu-north-1.elb.amazonaws.com/api/v1"
    };
